CREATE TABLE Player (
    PlayerID SERIAL PRIMARY KEY,
	PlayerName VARCHAR(50) NOT NULL
);
CREATE TABLE Team (
	TeamID SERIAL PRIMARY KEY,
	TeamName VARCHAR(50) NOT NULL
);
CREATE TABLE Wicket (
	WicketTypeID SERIAL PRIMARY KEY,
	Bowled INT NOT NULL,
	Caught INT NOT NULL,
	Runout INT NOT NULL,
	LBW INT NOT NULL,
	Other INT NOT NULL
);
CREATE TABLE MatchPlayers (
	MatchPlayersID SERIAL PRIMARY KEY,
	MatchID INT NOT NULL,
	PlayerID INT NOT NULL,
	TeamID INT NOT NULL,
	FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID),
	FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
);
CREATE TABLE BattingCard (
	BattingCardID SERIAL PRIMARY KEY,
	MatchID INT NOT NULL,
	PlayerID INT NOT NULL,
	TeamID INT NOT NULL,
	WicketTypeID INT,
	BattingStyle VARCHAR(50) NOT NULL,
	RunsScored INT NOT NULL,
	BallsFaced INT NOT NULL,
	Fours INT NOT NULL,
	Sixes INT NOT NULL,
	StrikeRate DECIMAL(5,2),
	IsOut BOOLEAN NOT NULL,
	Innings INT NOT NULL,
	FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID),
	FOREIGN KEY (TeamID) REFERENCES Team(TeamID),
	FOREIGN KEY (WicketTypeID) REFERENCES Wicket(WicketTypeID)
);
CREATE TABLE BowlingCard (
	BowlingCardID SERIAL PRIMARY KEY,
	PlayerID INT NOT NULL,
	MatchID INT NOT NULL,
	TeamID INT NOT NULL,
	BowlingOppositionTeamID INT NOT NULL,
	Innings SMALLINT NOT NULL,
	OversBalled SMALLINT NOT NULL,
	TotalBalls SMALLINT NOT NULL,
	Maidens SMALLINT NOT NULL,
	RunsConceded SMALLINT NOT NULL,
	WicketsTaken SMALLINT NOT NULL,
	EconomyRate DECIMAL(4,2) NOT NULL,
	DotBalls SMALLINT NOT NULL,
	FoursGiven SMALLINT NOT NULL,
	SixesGiven SMALLINT NOT NULL,
	WidesBowled SMALLINT NOT NULL,
	NoBalls SMALLINT NOT NULL,
	FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID),
	FOREIGN KEY (TeamID) REFERENCES Team(TeamID),
	FOREIGN KEY (BowlingOppositionTeamID) REFERENCES Team(TeamID)
);
CREATE TABLE Referee (
	RefereeID SERIAL PRIMARY KEY,
	RefereeName VARCHAR(50) NOT NULL
);
CREATE TABLE Umpire (
	UmpireID SERIAL PRIMARY KEY,
	UmpireName VARCHAR(50) NOT NULL
);
CREATE TABLE Series (
	SeriesID SERIAL PRIMARY KEY,
	SeriesName VARCHAR(50) NOT NULL
);
CREATE TABLE Venue (
	VenueID SERIAL PRIMARY KEY,
	VenueStadium VARCHAR(50) NOT NULL,
	VenueCity VARCHAR(50) NOT NULL,
	VenueCountry VARCHAR(50) NOT NULL
);
CREATE TABLE Match (
	MatchID SERIAL PRIMARY KEY,
	RefereeID INT NOT NULL,
	UmpireID INT NOT NULL,
	SeriesID INT NOT NULL,
	VenueID INT NOT NULL,
	Team1ID INT NOT NULL,
	Team2ID INT NOT NULL,
	TossWinnerTeamID INT NOT NULL,
	MatchWinnerTeamID INT NOT NULL,
	TossChoice VARCHAR(50),
	MatchResult VARCHAR(50),
	ManOfTheMatch VARCHAR(50),
	DebutPlayers VARCHAR(50),
	MatchName VARCHAR(50),
	MatchNo INT NOT NULL,
	MatchDate DATE,
	MatchFormat VARCHAR(50),
	FOREIGN KEY (RefereeID) REFERENCES Referee(RefereeID),
	FOREIGN KEY (UmpireID) REFERENCES Umpire(UmpireID),
	FOREIGN KEY (SeriesID) REFERENCES Series(SeriesID),
	FOREIGN KEY (VenueID) REFERENCES Venue(VenueID),
	FOREIGN KEY (Team1ID) REFERENCES Team(TeamID),
	FOREIGN KEY (Team2ID) REFERENCES Team(TeamID),
	FOREIGN KEY (TossWinnerTeamID) REFERENCES Team(TeamID),
	FOREIGN KEY (MatchWinnerTeamID) REFERENCES Team(TeamID)
);
CREATE TABLE TeamCaptain (
	CaptainID SERIAL PRIMARY KEY,
	MatchID INT NOT NULL,
	PlayerID INT NOT NULL,
	TeamID INT NOT NULL,
	FOREIGN KEY (MatchID) REFERENCES Match(MatchID),
	FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID),
	FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
)
